# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: method.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'method.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmethod.proto\"-\n\x0cMethodsProto\x12\x1d\n\x07methods\x18\x01 \x03(\x0b\x32\x0c.MethodProto\"\x93\x02\n\x0bMethodProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08notation\x18\x02 \x02(\t\x12\r\n\x05stage\x18\x03 \x02(\x05\x12\x14\n\x0cruleoffsFrom\x18\x04 \x01(\x05\x12\x15\n\rruleoffsEvery\x18\x05 \x02(\x05\x12%\n\rstandardCalls\x18\x06 \x01(\x0b\x32\x0e.StandardCalls\x12\x1f\n\x0b\x63ustomCalls\x18\t \x03(\x0b\x32\n.CallProto\x12\r\n\x05magic\x18\x07 \x02(\x05\x12\x32\n\x0e\x63lassification\x18\x08 \x02(\x0e\x32\x1a.MethodClassificationProto\x12\x1d\n\x15nameHasClassification\x18\n \x01(\x08\"h\n\tCallProto\x12\x0c\n\x04name\x18\x06 \x02(\t\x12\x0e\n\x06symbol\x18\x01 \x02(\t\x12\x10\n\x08notation\x18\x02 \x02(\t\x12\r\n\x05\x66rom_\x18\x03 \x01(\x05\x12\r\n\x05\x65very\x18\x04 \x02(\x05\x12\r\n\x05\x63over\x18\x05 \x02(\x05\"K\n\rStandardCalls\x12\x13\n\x0b\x62obNotation\x18\x01 \x02(\t\x12\x16\n\x0esingleNotation\x18\x02 \x02(\t\x12\r\n\x05\x65very\x18\x03 \x02(\x05*\x98\x01\n\x19MethodClassificationProto\x12\x08\n\x04None\x10\x00\x12\x0f\n\x0bTreblePlace\x10\x01\x12\x0b\n\x07\x44\x65light\x10\x02\x12\x07\n\x03\x42ob\x10\x03\x12\x08\n\x04Jump\x10\x04\x12\x0c\n\x08\x41lliance\x10\x05\x12\n\n\x06Hybrid\x10\x06\x12\r\n\tTrebleBob\x10\x07\x12\t\n\x05Place\x10\x08\x12\x0c\n\x08Surprise\x10\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'method_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METHODCLASSIFICATIONPROTO']._serialized_start=525
  _globals['_METHODCLASSIFICATIONPROTO']._serialized_end=677
  _globals['_METHODSPROTO']._serialized_start=16
  _globals['_METHODSPROTO']._serialized_end=61
  _globals['_METHODPROTO']._serialized_start=64
  _globals['_METHODPROTO']._serialized_end=339
  _globals['_CALLPROTO']._serialized_start=341
  _globals['_CALLPROTO']._serialized_end=445
  _globals['_STANDARDCALLS']._serialized_start=447
  _globals['_STANDARDCALLS']._serialized_end=522
# @@protoc_insertion_point(module_scope)
