# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: method.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'method.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmethod.proto\"-\n\x0cMethodsProto\x12\x1d\n\x07methods\x18\x01 \x03(\x0b\x32\x0c.MethodProto\"\xf2\x01\n\x0bMethodProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08notation\x18\x02 \x02(\t\x12\r\n\x05stage\x18\x03 \x02(\x05\x12\x14\n\x0cruleoffsFrom\x18\x04 \x02(\x05\x12\x15\n\rruleoffsEvery\x18\x05 \x02(\x05\x12&\n\x05\x63\x61lls\x18\x06 \x03(\x0b\x32\x17.MethodProto.CallsEntry\x12\r\n\x05magic\x18\x07 \x02(\x05\x12\x16\n\x0e\x63lassification\x18\x08 \x02(\t\x1a\x38\n\nCallsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.CallProto:\x02\x38\x01\"Z\n\tCallProto\x12\x0e\n\x06symbol\x18\x01 \x02(\t\x12\x10\n\x08notation\x18\x02 \x02(\t\x12\r\n\x05\x66rom_\x18\x03 \x02(\x05\x12\r\n\x05\x65very\x18\x04 \x02(\x05\x12\r\n\x05\x63over\x18\x05 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'method_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METHODPROTO_CALLSENTRY']._loaded_options = None
  _globals['_METHODPROTO_CALLSENTRY']._serialized_options = b'8\001'
  _globals['_METHODSPROTO']._serialized_start=16
  _globals['_METHODSPROTO']._serialized_end=61
  _globals['_METHODPROTO']._serialized_start=64
  _globals['_METHODPROTO']._serialized_end=306
  _globals['_METHODPROTO_CALLSENTRY']._serialized_start=250
  _globals['_METHODPROTO_CALLSENTRY']._serialized_end=306
  _globals['_CALLPROTO']._serialized_start=308
  _globals['_CALLPROTO']._serialized_end=398
# @@protoc_insertion_point(module_scope)
