package com.jd565.methods.generate

import com.jpd.MethodProto

data class CallAndRuleoffs(
    val calls: CallDetails,
    val ruleoffsEvery: Int,
    val ruleoffsFrom: Int,
)

// Standard calls and rule offs for various methods which aren't in line with what would get generated by default
val customCalls: Map<String, CallAndRuleoffs> = mapOf(
    "Antelope Place Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle("145.3.1", "145.3.123", every = 10, from = -2),
        ruleoffsEvery = 10, ruleoffsFrom = 1,
    ),
    "Banana Doubles" to CallAndRuleoffs(
        CallDetails.Custom(
            listOf(
                MethodProto.CallProto("Lead-End Bob", "-", "125", 0, 8),
                MethodProto.CallProto("Half-Lead Bob", "h", "145", -4, 8),
            ),
        ),
        ruleoffsEvery = 4, ruleoffsFrom = 0,
    ),
    "Double Norwich Court Bob Caters" to CallAndRuleoffs(
        CallDetails.BobAndSingle("3", "123", every = 18, from = 4),
        ruleoffsEvery = 18, ruleoffsFrom = 0,
    ),
    "Double Norwich Court Bob Cinques" to CallAndRuleoffs(
        CallDetails.BobAndSingle("3", "123", every = 22, from = 4),
        ruleoffsEvery = 22, ruleoffsFrom = 0,
    ),
    "Erin Caters" to CallAndRuleoffs(
        CallDetails.BobAndSingle("7", "789", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Cinques" to CallAndRuleoffs(
        CallDetails.BobAndSingle("9", "90E", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle(null, "345", every = 6, from = -2),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Octuples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("C", "CDF", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Septuples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("A", "ABC", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Sextuples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("E", "ETA", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Erin Triples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5", "567", every = 6, from = -5),
        ruleoffsEvery = 6, ruleoffsFrom = -5,
    ),
    "Original Caters" to CallAndRuleoffs(
        CallDetails.BobAndSingle("7", "789", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = 0,
    ),
    "Original Cinques" to CallAndRuleoffs(
        CallDetails.BobAndSingle("9", "90E", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = 0,
    ),
    "Original Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle("3", "345", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = 0,
    ),
    "Original Triples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5", "567", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = 0,
    ),
    "Scientific Triples" to CallAndRuleoffs(
        CallDetails.Custom(
            listOf(
                MethodProto.CallProto("Red", "-", "3.7.3", 30, 6),
                MethodProto.CallProto("Blue", "-", "3.7.3", 30, 15),
                MethodProto.CallProto("Green", "-", "3.7.3", 30, 23),
            ),
        ),
        ruleoffsEvery = 30, ruleoffsFrom = 0,
    ),
    "Shipway Minor" to CallAndRuleoffs(
        CallDetails.BobAndSingle("34", "3456", every = 8, from = 2),
        ruleoffsEvery = 8, ruleoffsFrom = 2,
    ),
    "Shipway Major" to CallAndRuleoffs(
        CallDetails.BobAndSingle("36", "3678", every = 8, from = 2),
        ruleoffsEvery = 8, ruleoffsFrom = 2,
    ),
    "Shipway Royal" to CallAndRuleoffs(
        CallDetails.BobAndSingle("38", "3890", every = 8, from = 2),
        ruleoffsEvery = 8, ruleoffsFrom = 2,
    ),
    "Stedman Caters" to CallAndRuleoffs(
        CallDetails.BobAndSingle("7", "789", every = 6, from = -3),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Cinques" to CallAndRuleoffs(
        CallDetails.BobAndSingle("9", "90E", every = 6, from = -3),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle(null, "45", every = 6, from = 0),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Septuples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("A", "ABC", every = 6, from = -3),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Sextuples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("E", "ETA", every = 6, from = -3),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Triples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5", "567", every = 6, from = -3),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman No.2 Jump Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle(null, "45", every = 6, from = 0),
        ruleoffsEvery = 6, ruleoffsFrom = -3,
    ),
    "Stedman Jump Triples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5", "567", every = 6, from = 1),
        ruleoffsEvery = 6, ruleoffsFrom = 1,
    ),
    "Titanic Cinques" to CallAndRuleoffs(
        CallDetails.BobAndSingle("9", "90E", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Titanic Doubles" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Titanic Triples" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5", "567", every = 2, from = -1),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Minimus" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Doubles" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Minor" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Triples" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Major" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Caters" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Royal" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Cinques" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Plain Hunt Maximus" to CallAndRuleoffs(
        CallDetails.Custom(emptyList()),
        ruleoffsEvery = 2, ruleoffsFrom = -1,
    ),
    "Bristol Surprise Maximus" to CallAndRuleoffs(
        CallDetails.BobAndSingle("14", "1234", every = 48, from = 0),
        ruleoffsEvery = 48, ruleoffsFrom = 0,
    ),
    "Solihull Bob Doubles" to CallAndRuleoffs(
        CallDetails.BobAndSingle("5.1", "5.123", every = 10, from = -1),
        ruleoffsEvery = 10, ruleoffsFrom = 0,
    ),
)
