package com.jd565.methods.generate

val topMethods = mapOf(
    4 to listOf(
        "Plain Bob Minimus",
    ),
    5 to listOf(
        "Plain Bob Doubles",
        "Grandsire Doubles",
        "Stedman Doubles",
    ),
    6 to listOf(
        "Plain Bob Minor",
        "St Clement's College Bob Minor",
        "Little Bob Minor",
        "Kent Treble Bob Minor",
        "Oxford Treble Bob Minor",
        "Cambridge Surprise Minor",
        "Norwich Surprise Minor",
        "London Surprise Minor",
    ),
    7 to listOf(
        "Plain Bob Triples",
        "Grandsire Triples",
        "Stedman Triples",
        "Single Oxford Bob Triples",
        "Erin Triples",
    ),
    8 to listOf(
        "Plain Bob Major",
        "Little Bob Major",
        "Double Norwich Court Bob Major",
        "Double Oxford Bob Major",
        "Duffield Major",
        "Kent Treble Bob Major",
        "Oxford Treble Bob Major",
        "Cambridge Surprise Major",
        "Yorkshire Surprise Major",
        "Superlative Surprise Major",
        "Cornwall Surprise Major",
        "Lessness Surprise Major",
        "Bristol Surprise Major",
        "London Surprise Major",
        "Rutland Surprise Major",
        "Lincolnshire Surprise Major",
        "Pudsey Surprise Major",
        "Glasgow Surprise Major",
        "Belfast Surprise Major",
        "Deva Surprise Major",
        "Ytterbium Surprise Major",
        "Adelaide Surprise Major",
        "Frodsham Surprise Major",
        "Jorvik Surprise Major",
        "Cooktown Orchid Delight Major",
        "Speedball Surprise Major",
        "Jovium Surprise Major",
        "Bolonium Surprise Major",
        "Lancashire Surprise Major",
        "Mareham Delight Major",
        "Rook and Gaskill Surprise Major",
        "Buckfastleigh Surprise Major",
        "Carolina Reaper Treble Bob Major",
        "Turramurra Surprise Major",
        "Painswick Surprise Major",
        "Falmouth Surprise Major",
        "Uxbridge Surprise Major",
        "Ealing Surprise Major",
        "Kenninghall Surprise Major",
        "Ely Surprise Major",
        "York Surprise Major",
        "Double Dublin Surprise Major",
        "Venusium Surprise Major",
        "Malpas Surprise Major",
        "Chenies Surprise Major",
        "Cat's-Eye Surprise Major",
        "Cassiobury Surprise Major",
        "Cray Surprise Major",
        "Ipswich Surprise Major",
        "Jersey Surprise Major",
        "Lindum Surprise Major",
        "Preston Surprise Major",
        "Tavistock Surprise Major",
        "Watford Surprise Major",
        "Wembley Surprise Major",
        "Whalley Surprise Major",
    ),
    9 to listOf(
        "Plain Bob Caters",
        "Grandsire Caters",
        "Stedman Caters",
    ),
    10 to listOf(
        "Yorkshire Surprise Royal",
        "Cambridge Surprise Royal",
        "London No. 3 Surprise Royal",
        "Bristol Surprise Royal",
    ),
    11 to listOf(
        "Stedman Cinques",
    ),
    12 to listOf(
        "Cambridge Surprise Maximus",
        "Bristol Surprise Maximus",
    ),
)
